spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 200 # 일대다 관계(컬렉션) 에서 fetch join으로 최적화를 하면 페이징이 안되기 때문에 LAZY로 가져와야 하는데 성능최적화를 위해 batch로 가져온다. 1000개 정도가 최대치 이다.
        use_sql_comments: true # queryDSL의 실행 query를 보여줌
    open-in-view: true
    data:
      web:
        pageable:
          default-page-size: 10 # 한 페이지에 보여주는 갯수
          max-page-size: 2000 # 최대 페이지 갯수


logging:
  lever:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 바인딩된 파라미터도 볼 수 있음